    window.VOCABULARY_CONFIG = {
        chapter: "11",
        title: "11과 어휘 학습",
        subtitle: "일과 직장 생활에 필요한 어휘를 익힙니다.",
        languages: [
                "en",
                "vi",
                "mn",
                "ar",
                "kk",
                "th"
        ],
        defaultLang: "none",
        quizModes: [
                "meaning",
                "choseong",
                "image"
        ],
        storageKey: "c11-vocabulary-standard",
        categories: [
                {
                        id: "all",
                        label: "전체"
                },
                {
                        id: "work",
                        label: "근무 조건"
                },
                {
                        id: "profile",
                        label: "지원 조건"
                },
                {
                        id: "ability",
                        label: "역량·태도"
                },
                {
                        id: "people",
                        label: "직장 사람들"
                },
                {
                        id: "company",
                        label: "회사·복지"
                }
        ],
        words: [
                {
                        id: "c11-vocab-01",
                        ko: "아르바이트",
                        meaning: "정해진 시간 동안 임시로 하는 일.",
                        pos: "명사",
                        category: "work",
                        example: "",
                        vi: "việc làm thêm",
                        ja: "アルバイト",
                        zh: "兼职 / 打工",
                        image: "../assets/c11/vocabulary/images/split/c11_02_TL.webp",
                        imageAlt: "아르바이트 그림 카드",
                        quizImage: "../assets/c11/vocabulary/images/masked/c11_02_TL_masked.webp",
                        quizImageAlt: "아르바이트 그림 카드"
                },
                {
                        id: "c11-vocab-02",
                        ko: "근무 시간",
                        meaning: "일을 하는 정해진 시간.",
                        pos: "명사",
                        category: "work",
                        example: "",
                        vi: "thời gian làm việc",
                        ja: "勤務時間",
                        zh: "工作时间",
                        image: "../assets/c11/vocabulary/images/split/c11_02_TR.webp",
                        imageAlt: "근무 시간 그림 카드",
                        quizImage: "../assets/c11/vocabulary/images/masked/c11_02_TR_masked.webp",
                        quizImageAlt: "근무 시간 그림 카드"
                },
                {
                        id: "c11-vocab-03",
                        ko: "업무",
                        meaning: "직장에서 맡아서 하는 일.",
                        pos: "명사",
                        category: "work",
                        example: "",
                        vi: "nhiệm vụ, công việc",
                        ja: "業務",
                        zh: "业务",
                        image: "../assets/c11/vocabulary/images/split/c11_02_BL.webp",
                        imageAlt: "업무 그림 카드",
                        quizImage: "../assets/c11/vocabulary/images/masked/c11_02_BL_masked.webp",
                        quizImageAlt: "업무 그림 카드"
                },
                {
                        id: "c11-vocab-04",
                        ko: "시급",
                        meaning: "한 시간 일하고 받는 돈.",
                        pos: "명사",
                        category: "work",
                        example: "",
                        vi: "lương theo giờ",
                        ja: "時給",
                        zh: "时薪",
                        image: "../assets/c11/vocabulary/images/split/c11_02_BR.webp",
                        imageAlt: "시급 그림 카드",
                        quizImage: "../assets/c11/vocabulary/images/masked/c11_02_BR_masked.webp",
                        quizImageAlt: "시급 그림 카드"
                },
                {
                        id: "c11-vocab-05",
                        ko: "성별",
                        meaning: "남자와 여자의 구분.",
                        pos: "명사",
                        category: "profile",
                        example: "",
                        vi: "giới tính",
                        ja: "性別",
                        zh: "性别",
                        image: "../assets/c11/vocabulary/images/split/c11_03_TL.webp",
                        imageAlt: "성별 그림 카드",
                        quizImage: "../assets/c11/vocabulary/images/masked/c11_03_TL_masked.webp",
                        quizImageAlt: "성별 그림 카드"
                },
                {
                        id: "c11-vocab-06",
                        ko: "연령",
                        meaning: "나이.",
                        pos: "명사",
                        category: "profile",
                        example: "",
                        vi: "tuổi tác",
                        ja: "年齢",
                        zh: "年龄",
                        image: "../assets/c11/vocabulary/images/split/c11_03_TR.webp",
                        imageAlt: "연령 그림 카드",
                        quizImage: "../assets/c11/vocabulary/images/masked/c11_03_TR_masked.webp",
                        quizImageAlt: "연령 그림 카드"
                },
                {
                        id: "c11-vocab-07",
                        ko: "성실하다",
                        meaning: "정성스럽고 참된 태도로 일하는 것.",
                        pos: "형용사",
                        category: "profile",
                        example: "",
                        vi: "thành thật, chăm chỉ",
                        ja: "誠実だ",
                        zh: "诚实",
                        image: "../assets/c11/vocabulary/images/split/c11_03_BL.webp",
                        imageAlt: "성실하다 그림 카드",
                        quizImage: "../assets/c11/vocabulary/images/masked/c11_03_BL_masked.webp",
                        quizImageAlt: "성실하다 그림 카드"
                },
                {
                        id: "c11-vocab-08",
                        ko: "꼼꼼하다",
                        meaning: "빈틈이 없이 자세하고 차분한 것.",
                        pos: "형용사",
                        category: "profile",
                        example: "",
                        vi: "tỉ mỉ, cẩn thận",
                        ja: "几帳面だ",
                        zh: "仔细",
                        image: "../assets/c11/vocabulary/images/split/c11_03_BR.webp",
                        imageAlt: "꼼꼼하다 그림 카드",
                        quizImage: "../assets/c11/vocabulary/images/masked/c11_03_BR_masked.webp",
                        quizImageAlt: "꼼꼼하다 그림 카드"
                },
                {
                        id: "c11-vocab-09",
                        ko: "경험이 많다",
                        meaning: "어떤 일을 많이 해 본 것.",
                        pos: "표현",
                        category: "ability",
                        example: "",
                        vi: "có nhiều kinh nghiệm",
                        ja: "経験が多い",
                        zh: "经验丰富",
                        image: "../assets/c11/vocabulary/images/split/c11_04_TL.webp",
                        imageAlt: "경험이 많다 그림 카드",
                        quizImage: "../assets/c11/vocabulary/images/masked/c11_04_TL_masked.webp",
                        quizImageAlt: "경험이 많다 그림 카드"
                },
                {
                        id: "c11-vocab-10",
                        ko: "실력이 있다",
                        meaning: "어떤 일을 잘 할 수 있는 능력이 있는 것.",
                        pos: "표현",
                        category: "ability",
                        example: "",
                        vi: "có thực lực",
                        ja: "実力がある",
                        zh: "有实力",
                        image: "../assets/c11/vocabulary/images/split/c11_04_TR.webp",
                        imageAlt: "실력이 있다 그림 카드",
                        quizImage: "../assets/c11/vocabulary/images/masked/c11_04_TR_masked.webp",
                        quizImageAlt: "실력이 있다 그림 카드"
                },
                {
                        id: "c11-vocab-11",
                        ko: "이해가 빠르다",
                        meaning: "다른 사람의 말이나 상황을 빨리 알아듣는 것.",
                        pos: "표현",
                        category: "ability",
                        example: "",
                        vi: "hiểu nhanh",
                        ja: "理解が速い",
                        zh: "理解快",
                        image: "../assets/c11/vocabulary/images/split/c11_04_BL.webp",
                        imageAlt: "이해가 빠르다 그림 카드",
                        quizImage: "../assets/c11/vocabulary/images/masked/c11_04_BL_masked.webp",
                        quizImageAlt: "이해가 빠르다 그림 카드"
                },
                {
                        id: "c11-vocab-12",
                        ko: "최선을 다하다",
                        meaning: "자신의 모든 힘과 노력을 다하는 것.",
                        pos: "표현",
                        category: "ability",
                        example: "",
                        vi: "cố gắng hết sức",
                        ja: "最善を尽くす",
                        zh: "尽力而为",
                        image: "../assets/c11/vocabulary/images/split/c11_04_BR.webp",
                        imageAlt: "최선을 다하다 그림 카드",
                        quizImage: "../assets/c11/vocabulary/images/masked/c11_04_BR_masked.webp",
                        quizImageAlt: "최선을 다하다 그림 카드"
                },
                {
                        id: "c11-vocab-13",
                        ko: "보고서 작성을 잘하다",
                        meaning: "보고 문서를 잘 만드는 것.",
                        pos: "표현",
                        category: "ability",
                        example: "",
                        vi: "viết báo cáo giỏi",
                        ja: "報告書の作成が上手だ",
                        zh: "报告写得好",
                        image: "../assets/c11/vocabulary/images/split/c11_05_TL.webp",
                        imageAlt: "보고서 작성을 잘하다 그림 카드",
                        quizImage: "../assets/c11/vocabulary/images/masked/c11_05_TL_masked.webp",
                        quizImageAlt: "보고서 작성을 잘하다 그림 카드"
                },
                {
                        id: "c11-vocab-14",
                        ko: "대인 관계가 원만하다",
                        meaning: "다른 사람들과 사이좋게 잘 지내는 것.",
                        pos: "표현",
                        category: "ability",
                        example: "",
                        vi: "quan hệ xã hội tốt",
                        ja: "対人関係が円満だ",
                        zh: "人际关系圆满",
                        image: "../assets/c11/vocabulary/images/split/c11_05_TR.webp",
                        imageAlt: "대인 관계가 원만하다 그림 카드",
                        quizImage: "../assets/c11/vocabulary/images/masked/c11_05_TR_masked.webp",
                        quizImageAlt: "대인 관계가 원만하다 그림 카드"
                },
                {
                        id: "c11-vocab-15",
                        ko: "신입 사원",
                        meaning: "회사에 새로 들어온 직원.",
                        pos: "명사",
                        category: "people",
                        example: "",
                        vi: "nhân viên mới",
                        ja: "新入社員",
                        zh: "新职员",
                        image: "../assets/c11/vocabulary/images/split/c11_05_BL.webp",
                        imageAlt: "신입 사원 그림 카드",
                        quizImage: "../assets/c11/vocabulary/images/masked/c11_05_BL_masked.webp",
                        quizImageAlt: "신입 사원 그림 카드"
                },
                {
                        id: "c11-vocab-16",
                        ko: "동료",
                        meaning: "직장에서 직급이 비슷하거나 같은 사람.",
                        pos: "명사",
                        category: "people",
                        example: "",
                        vi: "đồng nghiệp",
                        ja: "同僚",
                        zh: "同事",
                        image: "../assets/c11/vocabulary/images/split/c11_05_BR.webp",
                        imageAlt: "동료 그림 카드",
                        quizImage: "../assets/c11/vocabulary/images/masked/c11_05_BR_masked.webp",
                        quizImageAlt: "동료 그림 카드"
                },
                {
                        id: "c11-vocab-17",
                        ko: "직장 상사",
                        meaning: "직장에서 자기보다 직급이 높은 사람.",
                        pos: "명사",
                        category: "people",
                        example: "",
                        vi: "cấp trên",
                        ja: "職場の上司",
                        zh: "职场上司",
                        image: "../assets/c11/vocabulary/images/split/c11_06_TL.webp",
                        imageAlt: "직장 상사 그림 카드",
                        quizImage: "../assets/c11/vocabulary/images/masked/c11_06_TL_masked.webp",
                        quizImageAlt: "직장 상사 그림 카드"
                },
                {
                        id: "c11-vocab-18",
                        ko: "부하 직원",
                        meaning: "직장에서 자기보다 직급이 낮은 사람.",
                        pos: "명사",
                        category: "people",
                        example: "",
                        vi: "cấp dưới",
                        ja: "部下の職員",
                        zh: "部下职员",
                        image: "../assets/c11/vocabulary/images/split/c11_06_TR.webp",
                        imageAlt: "부하 직원 그림 카드",
                        quizImage: "../assets/c11/vocabulary/images/masked/c11_06_TR_masked.webp",
                        quizImageAlt: "부하 직원 그림 카드"
                },
                {
                        id: "c11-vocab-19",
                        ko: "대리",
                        meaning: "과장 아래의 직급.",
                        pos: "명사",
                        category: "people",
                        example: "",
                        vi: "trợ lý giám đốc",
                        ja: "代理",
                        zh: "代理",
                        image: "../assets/c11/vocabulary/images/split/c11_06_BL.webp",
                        imageAlt: "대리 그림 카드",
                        quizImage: "../assets/c11/vocabulary/images/masked/c11_06_BL_masked.webp",
                        quizImageAlt: "대리 그림 카드"
                },
                {
                        id: "c11-vocab-20",
                        ko: "과장",
                        meaning: "부장 아래, 대리 위의 직급.",
                        pos: "명사",
                        category: "people",
                        example: "",
                        vi: "trưởng khoa, quản đốc",
                        ja: "課長",
                        zh: "科长",
                        image: "../assets/c11/vocabulary/images/split/c11_06_BR.webp",
                        imageAlt: "과장 그림 카드",
                        quizImage: "../assets/c11/vocabulary/images/masked/c11_06_BR_masked.webp",
                        quizImageAlt: "과장 그림 카드"
                },
                {
                        id: "c11-vocab-21",
                        ko: "부장",
                        meaning: "회사의 한 부서를 책임지는 사람.",
                        pos: "명사",
                        category: "people",
                        example: "",
                        vi: "trưởng phòng",
                        ja: "部長",
                        zh: "部长",
                        image: "../assets/c11/vocabulary/images/split/c11_01_TL.webp",
                        imageAlt: "부장 그림 카드",
                        quizImage: "../assets/c11/vocabulary/images/masked/c11_01_TL_masked.webp",
                        quizImageAlt: "부장 그림 카드"
                },
                {
                        id: "c11-vocab-22",
                        ko: "대기업",
                        meaning: "규모가 아주 큰 회사.",
                        pos: "명사",
                        category: "company",
                        example: "",
                        vi: "công ty lớn, tập đoàn",
                        ja: "大企業",
                        zh: "大企业",
                        image: "../assets/c11/vocabulary/images/split/c11_01_TR.webp",
                        imageAlt: "대기업 그림 카드",
                        quizImage: "../assets/c11/vocabulary/images/masked/c11_01_TR_masked.webp",
                        quizImageAlt: "대기업 그림 카드"
                },
                {
                        id: "c11-vocab-23",
                        ko: "중소기업",
                        meaning: "규모가 크지 않은 회사.",
                        pos: "명사",
                        category: "company",
                        example: "",
                        vi: "doanh nghiệp vừa và nhỏ",
                        ja: "中小企業",
                        zh: "中小企业",
                        image: "../assets/c11/vocabulary/images/split/c11_01_BL.webp",
                        imageAlt: "중소기업 그림 카드",
                        quizImage: "../assets/c11/vocabulary/images/masked/c11_01_BL_masked.webp",
                        quizImageAlt: "중소기업 그림 카드"
                },
                {
                        id: "c11-vocab-24",
                        ko: "연봉이 높다",
                        meaning: "일 년 동안 받는 월급이 많은 것.",
                        pos: "표현",
                        category: "company",
                        example: "",
                        vi: "lương năm cao",
                        ja: "年俸が高い",
                        zh: "年薪高",
                        image: "../assets/c11/vocabulary/images/split/c11_01_BR.webp",
                        imageAlt: "연봉이 높다 그림 카드",
                        quizImage: "../assets/c11/vocabulary/images/masked/c11_01_BR_masked.webp",
                        quizImageAlt: "연봉이 높다 그림 카드"
                },
                {
                        id: "c11-vocab-25",
                        ko: "출퇴근 시간이 자유롭다",
                        meaning: "회사에 오고 가는 시간이 자유로운 것.",
                        pos: "표현",
                        category: "company",
                        example: "",
                        vi: "thời gian đi làm và tan làm tự do",
                        ja: "出退勤時間が自由だ",
                        zh: "上下班时间自由",
                        image: "../assets/c11/vocabulary/images/split/c11_07_TL.webp",
                        imageAlt: "출퇴근 시간이 자유롭다 그림 카드",
                        quizImage: "../assets/c11/vocabulary/images/masked/c11_07_TL_masked.webp",
                        quizImageAlt: "출퇴근 시간이 자유롭다 그림 카드"
                },
                {
                        id: "c11-vocab-26",
                        ko: "승진 기회가 많다",
                        meaning: "직급이 올라갈 기회가 많은 것.",
                        pos: "표현",
                        category: "company",
                        example: "",
                        vi: "có nhiều cơ hội thăng tiến",
                        ja: "昇進の機会が多い",
                        zh: "晋升机会多",
                        image: "../assets/c11/vocabulary/images/split/c11_07_TR.webp",
                        imageAlt: "승진 기회가 많다 그림 카드",
                        quizImage: "../assets/c11/vocabulary/images/masked/c11_07_TR_masked.webp",
                        quizImageAlt: "승진 기회가 많다 그림 카드"
                },
                {
                        id: "c11-vocab-27",
                        ko: "휴가가 길다",
                        meaning: "쉴 수 있는 날이 긴 것.",
                        pos: "표현",
                        category: "company",
                        example: "",
                        vi: "kỳ nghỉ dài",
                        ja: "休暇が長い",
                        zh: "假期长",
                        image: "../assets/c11/vocabulary/images/split/c11_07_BL.webp",
                        imageAlt: "휴가가 길다 그림 카드",
                        quizImage: "../assets/c11/vocabulary/images/masked/c11_07_BL_masked.webp",
                        quizImageAlt: "휴가가 길다 그림 카드"
                },
                {
                        id: "c11-vocab-28",
                        ko: "직급",
                        meaning: "회사나 조직에서 책임과 역할의 높낮이를 나타내는 등급.",
                        note: "(4급 어휘, 시험 X)",
                        pos: "명사",
                        category: "people",
                        example: "",
                        quiz: false,
                        image: "../assets/c11/vocabulary/images/split/c11_08_TL.webp",
                        imageAlt: "직급 피라미드 그림 카드",
                        quizImage: "../assets/c11/vocabulary/images/masked/c11_08_TL_masked.webp",
                        quizImageAlt: "직급 피라미드 그림 카드"
                }
        ]
};
    window.MULTILANG_CONFIG = {
        langs: window.VOCABULARY_CONFIG.languages || ["en", "vi", "mn", "ar", "kk", "th"],
        defaultLang: window.VOCABULARY_CONFIG.defaultLang || "none"
    };

