"""Build the embedded public-domain MIDI library for C16 Chaos Orchestra."""

from __future__ import annotations

import base64
import hashlib
import textwrap
import urllib.request
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "c16" / "chaos-orchestra" / "classical-midi-data.js"

SOURCES = (
    {
        "id": "fur-elise",
        "mutopia_id": 931,
        "url": "https://www.mutopiaproject.org/ftp/BeethovenLv/WoO59/fur_Elise_WoO59/fur_Elise_WoO59.mid",
        "sha256": "1c12c21c7bbf4cf163896732672648a69d497636059837abd153c71abe50215a",
    },
    {
        "id": "eine-kleine",
        "mutopia_id": 900,
        "url": "https://www.mutopiaproject.org/ftp/MozartWA/KV525/eine-kleine-nachtmusik-mvt1/eine-kleine-nachtmusik-mvt1.mid",
        "sha256": "f8b6dc991df6e90e2e2e11d561ab2cf8fec47beda747c69984c3fef4b539506b",
    },
    {
        "id": "turkish-march",
        "mutopia_id": 108,
        "url": "https://www.mutopiaproject.org/ftp/MozartWA/KV331/KV331_3_RondoAllaTurca/KV331_3_RondoAllaTurca.mid",
        "sha256": "c14299cbdd34c8b2081da84dc06519ef8a52a0d589ee53c758d28b8e3d727d1c",
    },
    {
        "id": "bach-prelude",
        "mutopia_id": 5,
        "url": "https://www.mutopiaproject.org/ftp/BachJS/BWV846/wtk1-prelude1/wtk1-prelude1.mid",
        "sha256": "874e07d0479542971bfceaf420d6117da8d602d89d26eea4610e7dd1ef58bf26",
    },
    {
        "id": "symphony-five",
        "mutopia_id": 941,
        "url": "https://www.mutopiaproject.org/ftp/BeethovenLv/O67/Symphony5_1/Symphony5_1.mid",
        "sha256": "0ce1bca911ba8e6234fd2e474a9b6da4c968c5cfe85b0cccfe7e56505df52046",
    },
)


def javascript_string_chunks(data: bytes) -> str:
    encoded = base64.b64encode(data).decode("ascii")
    chunks = textwrap.wrap(encoded, width=120)
    return "[\n" + "\n".join(f"                '{chunk}'," for chunk in chunks) + "\n            ].join('')"


def build() -> None:
    entries: list[str] = []
    for source in SOURCES:
        with urllib.request.urlopen(source["url"], timeout=30) as response:
            payload = response.read()
        digest = hashlib.sha256(payload).hexdigest()
        if digest != source["sha256"]:
            raise RuntimeError(f"SHA-256 mismatch for {source['id']}: {digest}")

        page_url = f"https://www.mutopiaproject.org/cgibin/piece-info.cgi?id={source['mutopia_id']}"
        entries.append(
            "\n".join(
                (
                    f"        '{source['id']}': Object.freeze({{",
                    f"            mutopiaId: {source['mutopia_id']},",
                    "            license: 'Public Domain',",
                    f"            pageUrl: '{page_url}',",
                    f"            midiUrl: '{source['url']}',",
                    f"            sha256: '{digest}',",
                    f"            data: {javascript_string_chunks(payload)}",
                    "        })",
                )
            )
        )

    output = "\n".join(
        (
            "/* Generated by scripts/build-c16-classical-midi-data.py.",
            " * Source scores and MIDI engravings: Mutopia Project, Public Domain.",
            " */",
            "(() => {",
            "    'use strict';",
            "",
            "    window.C16ClassicalMidiLibrary = Object.freeze({",
            "        version: 1,",
            "        provider: 'Mutopia Project',",
            "        songs: Object.freeze({",
            ",\n".join(entries),
            "        })",
            "    });",
            "})();",
            "",
        )
    )
    OUTPUT.write_text(output, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    build()
